service: lambda-image-resizer-demo

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: ${opt:stage, 'prod'}
  region:  ${opt:region, 'eu-north-1'}
  memorySize: ${opt:memory, 1536}
  timeout: ${opt:timeout, 20}
  logRetentionInDays: ${param:logRetentionInDays, 7}
  versionFunctions: false
  httpApi:
    cors: true
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  stackTags:
    Usage: ${self:service}
  tags:
    Usage: ${self:service}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-iam-roles-per-function

package:
  individually: true

custom:
  imagesBucketArn: arn:aws:s3:::${self:custom.imagesBucketName}
  imagesBucketName: ${self:service}-some-random-value # SET THIS VALUE
  esbuild:
    bundle: true
    minify: true
    external:
      - sharp
    packagerOptions:
      scripts:
        - npm install --os=linux --cpu=arm64 sharp

functions:
  ImageConverter:
    handler: src/handler.handler
    description: Convert image
    events:
      - httpApi:
          method: POST
          path: /
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:PutObject
        Resource: "${self:custom.imagesBucketArn}/*"
    environment:
      BUCKET_NAME: ${self:custom.imagesBucketName}